<a href="https://colab.research.google.com/github/Ashwitharavula/ps_lab/blob/main/Lab-22/8/25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#write text to file
fp=open("example.txt","w")
fp.write("Hello,B.Tech students!\n")
fp.write("SR university")
fp.write(" suresh kumar\n")
#close file
fp.close()
print("data written successfully")

data written successfully


In [5]:
#Reading from a file
#open file in read mode
file=open("example.txt","r")
#read entire content
content=file.read()
print("file content:\n",content)
#close file
file.close()
#read line by line
file=open("example.txt","r")
line1=file.readline()
print("firstline:",line1)
line2=file.readline()
print("secondline:",line2)
line3=file.readline()
print("line:",line3)
file.close()



file content:
 Hello,B.Tech students!
SR university suresh kumar


In [6]:
#reading all lines into a list
file=open("example.txt","r")
lines=file.readlines()
print("All Lines as list:",lines)
file.close()

All Lines as list: ['Hello,B.Tech students!\n', 'SR university suresh kumar']


In [10]:
#appending data to an existing file
file=open("example.txt","a")
file.write("appending new data..\n")
file.close()

In [11]:
#using with statement
with open("example.txt","r")as fb:
  data=fb.read()
  print(data)

Hello,B.Tech students!
SR university suresh kumar
appending new data..
appending new data..



In [19]:
import csv
with open("data.csv","w",newline='')as fp:
  wr=csv.writer(fp)
  wr.writerows([["Name","age","course"],["aaa",21,"CSE"],["bbb",20,"ECE"]])
with open("data.csv","r")as file:
    re= csv.reader(file)
    for row in re:
      print(row)

['Name', 'age', 'course']
['aaa', '21', 'CSE']
['bbb', '20', 'ECE']


In [21]:
import numpy as np
#1D array
arr1=np.array([1,2,3,4])
print("1D Array:",arr1)
#2D array
arr2=np.array([[1,2,3],[4,5,6]])
print("2D array:\n",arr2)
#zeros array
zeros_arr=np.zeros((3,3))
print("zeros array:\n",zeros_arr)
#ones array
ones_arr=np.ones((2,4))
print("ones array:\n",ones_arr)
#range of numbers
range_arr=np.arange(0,10,2)
print("range array:\n",range_arr)
#random array
rand_arr=np.random.rand(2,3)
print("random array:\n",rand_arr)

1D Array: [1 2 3 4]
2D array:
 [[1 2 3]
 [4 5 6]]
zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
range array:
 [0 2 4 6 8]
random array:
 [[0.69581525 0.84154846 0.38662483]
 [0.63006064 0.87548736 0.24609044]]


In [23]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)#(rows,columns)
print("dimension:",arr.ndim)#2D Array
print("data type:",arr.dtype)#int64 or float64
print("Size:",arr.size)#total elements
print("item size:",arr.itemsize)#bytes per element

Shape: (2, 3)
dimension: 2
data type: int64
Size: 6
item size: 8


In [24]:
a=np.array([10,20,30,40,50])
print("first element:",a[0])
print("last element:",a[-1])
print("slice[1:4]:",a[1:4])
print("every second element:",a[::2])
#2D indexing
arr2=np.array([[1,2,3],[4,5,6]])
print("element at r1 col 2:",arr2[0,1])
print("second row",arr2[1,:])
print("second column:",arr2[:,1])

first element: 10
last element: 50
slice[1:4]: [20 30 40]
every second element: [10 30 50]
element at r1 col 2: 2
second row [4 5 6]
second column: [2 5]
